import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;

public class ThirdLab {

    public static void main(String[] args) throws Exception {

        PdfFont font = PdfFontFactory.createFont("Shrift.ttf", "CP1251", true);
        PdfWriter writer = new PdfWriter("res.pdf");
        PdfReader reader = new PdfReader("Shablon.pdf");
        PdfDocument pdf = new PdfDocument(reader, writer);
        Document document = new Document(pdf);
        document.setFont(font);
        Paragraph np = new Paragraph(new Text("Раффайзен банк"));
        np.setFixedPosition(35, 786, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("4362437414"));
        np.setFixedPosition(55, 750, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("342432595934"));
        np.setFixedPosition(198, 750, 100);
        np.setFontSize(10);
        document.add(np);
        String whoget = "Интерсвязь";
        np = new Paragraph(new Text(whoget));
        np.setFixedPosition(35, 737, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("1377238429"));
        np.setFixedPosition(353, 786, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("43278573402382"));
        np.setFixedPosition(353, 775, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("23423455394039"));
        np.setFixedPosition(353, 749, 100);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("3 марта"));
        np.setFixedPosition(192, (float) 683.7, 100);
        np.setFontSize(13);
        document.add(np);
        np = new Paragraph(new Text("18"));
        np.setFixedPosition((float) 250.4, (float) 683.7, 100);
        np.setFontSize(13);
        document.add(np);
        np = new Paragraph(new Text("1"));
        np.setFixedPosition(162, 681, 1000);
        np.setFontSize(14);
        document.add(np);
        np = new Paragraph(new Text(whoget));
        np.setFixedPosition(100, 638, 1000);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("ОАО Газпром Нефть"));
        np.setFixedPosition(100, 605, 1000);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("№5839 от 14 февраля 2018"));
        np.setFixedPosition(100, 580, 1000);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("Интернет и телефония"));
        np.setFixedPosition(65, 540, 1000);
        np.setFontSize(12);
        document.add(np);
        np = new Paragraph(new Text("1"));
        np.setFixedPosition(355, 540, 1000);
        np.setFontSize(12);
        document.add(np);
        np = new Paragraph(new Text("1"));
        np.setFixedPosition(322, 540, 1000);
        np.setFontSize(12);
        document.add(np);
        double price = 66.08; 
        np = new Paragraph(new Text(String.valueOf(price)));
        np.setFixedPosition(390, 540, 1000);
        np.setFontSize(12);
        document.add(np);
        np = new Paragraph(new Text(String.valueOf(price)));
        np.setFixedPosition(457, 540, 1000);
        np.setFontSize(12);
        document.add(np);
        np = new Paragraph(new Text(price + " руб."));
        np.setFixedPosition(450, 491, 1000);
        np.setFontSize(9);
        document.add(np);
        np = new Paragraph(new Text("0 руб."));
        np.setFixedPosition(450, 479, 1000);
        np.setFontSize(9);
        document.add(np);
        np = new Paragraph(new Text(price + " руб."));
        np.setFixedPosition(450, 466, 1000);
        np.setFontSize(9);
        document.add(np);
        np = new Paragraph(new Text("Исаков А. Д."));
        np.setFixedPosition(451, 334, 1000);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("Япаров Д. В."));
        np.setFixedPosition(237, 334, 1000);
        np.setFontSize(10);
        document.add(np);
        np = new Paragraph(new Text("1 на сумму " + price + " руб."));
        np.setFixedPosition(122, 451, 1000);
        np.setFontSize(9);
        document.add(np);
        document.close();
    }
}
